name: "Terraform Resource Action"
branding:
  icon: aperture
  color: orange
description: "Terraform resource port from Concourse. It is meant to ease portability across Github Actions and Concourse Pipelines."
inputs:
  env_name:
    description: "Name of the environment to manage, e.g. staging. A Terraform workspace will be created with this name."
    required: false
  terraform_source:
    description: "The relative path of the directory containing your Terraform configuration files. For example: if your .tf files are stored in a git repo called prod-config under a directory terraform-configs, you could do a get: prod-config in your pipeline with terraform_source: prod-config/terraform-configs/ as the source."
    required: true
  backend_config:
    description: "JSON object with the corresponding backend config"
    required: true
  backend_type:
    description: "We only support s3 and gcs for now"
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.env_name }}
    - ${{ inputs.terraform_source }}
    - ${{ inputs.backend_type }}
    - ${{ inputs.backend_config }}