name: Test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fetch Terraform Templates
      uses: actions/checkout@v2
      with:
        repository: "alfonsof/terraform-google-cloud-examples"
        path: terraforming-repo

    - name: "Terraform Apply"
      uses: ciriarte/terraform-actions@main
      with:
        env_name: "cutekoala"
        terraform_source: "terraforming-repo"
        backend_type: s3
        backend_config: ${{ secrets.BACKEND_CONFIG }}