name: Test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: "Terraform Apply"
      uses: ciriarte/terraform-actions@main
      with:
        env_name: "cutekoala"
        template_path: "./"
        terraform_source: "alfonsof/terraform-google-cloud-examples/blob/master/code/01-hello-world/"
        backend_type: s3
        backend_config: ${{ secrets.BACKEND_CONFIG }}

    - name: "TEST"
      run: echo "Blah"