name: Test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: "Terraform Apply"
      uses: ./
      with:
        template_path: ./
        terraform_source: alfonsof/terraform-google-cloud-examples/blob/master/code/01-hello-world/